server:  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3606/sample2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sample2
    password: sample2
    driver-class-name: com.mysql.cj.jdbc.Driver
  sample:
    datasource:
      url: jdbc:mysql://localhost:3506/sample?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: sample
      password: sample
      driver-class-name: com.mysql.cj.jdbc.Driver        flyway:    url: jdbc:mysql://localhost:3606/sample2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true    user: sample2    password: sample2    logging:  level:    root: info